[toolchain]
package_manager = "yarn"
build_command = "build-sbf"


[features]
resolution = true
skip-lint = false
seeds = true  # Змінюємо на булеве значення

[programs.localnet]
password_vault = "7zQRzCwC9sL5iHUdpkggFSGKcqq6THhNTWSdTrJyaoax"

[programs.devnet]
password_vault = "7zQRzCwC9sL5iHUdpkggFSGKcqq6THhNTWSdTrJyaoax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

